name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # -------------------------------------------------------------------
    # 1. CHECKOUT CODE
    # -------------------------------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v3

    # -------------------------------------------------------------------
    # 2. CONFIGURE AWS WITH OIDC
    # -------------------------------------------------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::730335466710:role/Sagar-ETL-Role-for-Github
        aws-region: us-east-1

    # -------------------------------------------------------------------
    # 3. SETUP TERRAFORM
    # -------------------------------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # -------------------------------------------------------------------
    # 4. INIT CONFIGURATION (uses S3 remote backend)
    # -------------------------------------------------------------------
    - name: Terraform Init
      run: terraform init -input=false

    # -------------------------------------------------------------------
    # 5. TERRAFORM PLAN
    # -------------------------------------------------------------------
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # -------------------------------------------------------------------
    # 9. APPLY ON DEV BRANCH
    # -------------------------------------------------------------------
    - name: Terraform Apply (dev only)
      if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
      run: terraform apply -auto-approve
